### PR TITLE
Core

### PR DESCRIPTION
**Pull request by MingShaneTong**
Same as the previous branch. Accidentally merged. 
Follows the white line.
Looks at the center row and move left and right wheel.
Moves fast at straight lines, slows down on curves.
Does not respond to obstacles.
The main function is in main.cpp.
robot.hpp renamed to helper.hpp
Ready for testing.

### CODE REVIEW

**Comment by lucassarten** [comment]
I can't get that code to run as it should. The robot corrects itself but ends up losing the line almost instantly. I don't see anything wrong with your code so did you use a different robot config.txt or some other dependency I'm missing?

**Comment by MingShaneTong** [comment]
I think the problem is that the wrong file is made. You need to change your makefile to main.cpp instead of robot.cpp because I have changed that to a class file.

**Comment by lucassarten** [comment]
It compiles fine but runs like this: https://i.imgur.com/GbMzKFr.gifv

**Comment by MingShaneTong** [comment]
I have added my exe. Try that one and tell me if it works.

**Comment by lucassarten** [comment]
That exe is different from the one I compiled for some reason but still the same result

**Comment by MingShaneTong** [comment]
I tried copying my files into a different folder but it still works for me. Do the images look alright on the i0.ppm?

**Comment by lucassarten** [comment]
Yeah I cant see a problem with it. Maybe just zip the whole thing and send it to me?

**Comment by lucassarten** [comment]
Never mind i0.ppm looks like this https://i.imgur.com/qS4r3Ic.png

**Comment by MingShaneTong** [comment]
I had that error a few days ago. You need to recompile the server cpp.

**Comment by lucassarten** [comment]
That fixed it. Thanks.

**Pull request merged**
